apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-replicaset-app
  template:
    metadata:
      labels:
        app: nginx-replicaset-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest